name: Enviar proyecto para el Hackathon
description: Envía tu proyecto 
title: "[Project] <title>"
labels: [Project, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: ¿Asististe al taller de GitHub?
    description: Seleccione ✅ si ha asistido al taller de GitHub
    options:
    - label: He asistido al Workshop de GitHub
      required: true
- type: input
  attributes:
    label: Nombre del proyecto
    description: Agregue un nombre a su proyecto.
  validations:
    required: true
- type: input
  attributes:
    label: Repositorio del proyecto
    description: Comparte el enlace del repositorio de GitHub de tu proyecto.
  validations:
    required: true
- type: input
  attributes:
    label: Project URL
    description: Comparta el enlace de demostración de tu proyecto o video de demostración.
  validations:
    required: true
- type: input
  attributes:
    label: Nombre de la Universidad/instituación
    description: Por favor agregue el nombre de la institución.
  validations:
    required: true
- type: textarea
  attributes:
    label: Descripción del Proyecto
    description: |
      Descripción del proyectoaEnlaces? ¿Referencias? ¡Cualquier cosa que nos dé más contexto sobre tu proyecto!

       Sugerencia: puede adjuntar detalles del proyecto: archivos pdf, presentación del proyecto, imágenes haciendo clic en esta área para resaltarla y luego arrastrando los archivos.
  validations:
    required: false
- type: dropdown
  attributes:
    label: Herramientas del GitHub Student Developer Pack Tools usadas
    description: |
      Los proyectos deben utilizar al menos una herramienta del Pack.
    multiple: true
    options:
      - Deepsource
      - Deepscan
      - pyCharm
      - Push Bots
      - Canva
      - Microsoft Azure
      - GitHub
      - ATOM
      - Mongo DB
      - Twilio
      - Pop SQL
      - Astra
      - WiseJ
      - LogDNA
      - Other
  validations:
    required: true
